### ISSUE TITLE
Logon Support

### ISSUE THREAD

**Issue by dwbolt** [ETPRI/Graph#38]
---------------------------------- have scaffold solution, schedule more robust system
name
password

topic node users

store password in relation attribute

**Comment by AmyFiori** [comment]
Some issues we're going to need to think about regarding logging in, and users in general:
Restricting who can make changes
- Have certain people marked as "administrators"
   - If we have a "users" topic, maybe also have an "administrators" topic?
   - Only they can add new users
   - Only they can reset a user's password if it's forgotten
   - Only they can remove users, either by trashing the whole node or marking them "not a user"
   - Only they and the user can change a user's information (name, etc.)

Protecting users' information
- If we have a "users" topic, make it impossible for anyone to trash it
- Make it impossible for other people (except for administrators) to:
   - Trash a user
   - Change a user's information
   - Mark a user as not a user (by deleting their relation to the "users" table, for instance)
   - Reset a user's password (to an auto-generated one)
- Make it impossible for ANYONE but the user to change their password to a new one they choose
- Make it impossible for ANYONE but the user to see their password, even with direct access to the DB
   - Store it in some coded form, not raw (like a hash)
   - When resetting it, have a one-use password automatically generated and emailed to the user
      - Then require the user to change their password when they log in

Recognizing users
- Users need to be treated differently from other data - harder to edit or delete
   - Need to be able to recognize them easily, even when they're shown in a people or relations table
      - Or maybe just be able to recognize them when opened for editing?
      - You can't actually change or trash a node from the table, so that might be OK
      - Probably still better to be able to see the difference right away, though
         - Not sure how to do that with a "users" topic, since the fact they're a user is stored in a relation
            - We don't usually look for relations when building people table
            - We don't usually look for relations to OTHER nodes when building relation table

Are there alternatives to users topic, and if so, are they better?
- Main alternative I can see so far is having a "user" label
   - Users could be marked as both "user" and "people" (neo4j allows multiple labels)
      - Or could be marked "user" instead of "people"
   - Could also have an "administrator" label
   - Either way, have to work on how to show them in tables, but I think I can do it
      - If we don't use multiple labels, make users and administrators show up on people table
      - If we do use multiple labels, show all types instead of just one in relations table
      - Either way, can probably get it working by making a few changes to metaData
   - Easier to immediately recognize a user (just check the node's label)
   - No need for special undeletable topic
   - Since this was my idea, I'm better able to see its benefits than those of the users topic
      - User label looks better to me, but I'm likely biased
      - Can you tell me why you like the users topic idea?

**Comment by dwbolt** [comment]
admin, admin org, user
....
